// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shzzgokojhucwewjukvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNoenpnb2tvamh1Y3dld2p1a3ZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NTk5ODEsImV4cCI6MjA2MDQzNTk4MX0.RSNdhBHKIfZih7G_T4qx0lIHisyRYF9h-pcnoqNGKFQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);